apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gethnodes.geth.example.com
spec:
  group: geth.example.com
  names:
    kind: GethNode
    listKind: GethNodeList
    plural: gethnodes
    singular: gethnode
  scope: Namespaced
  version: v1alpha1
